[public_keys]
sequencer_public_key = "204040e364c10f2bec9c1fe500a1cd4c247c89d650a01ed7e82caba867877c21"
sequencer_da_pub_key = "02588d202afcc1ee4ab5254c7847ec25b9a135bbda0f2bc69ee1a714749fd77dc9"
prover_da_pub_key = ""

[da]
# fill here
node_url = ""
# fill here
node_username = ""
# fill here
node_password = ""
network = "regtest"
tx_backup_dir = "resources/bitcoin/inscription_txs"
da_private_key = "56D08C2DDE7F412F80EC99A0A328F76688C904BD4D1435281EFC9270EC8C8707"

[storage]
# The path to the rollup's data directory. Paths that do not begin with `/` are interpreted as relative paths.
path = "resources/dbs/batch-prover-db"
db_max_open_files = 5000

[rpc]
# the host and port to bind the rpc server for
bind_host = "127.0.0.1"
bind_port = 12346
enable_subscriptions = false

[runner]
sequencer_client_url = "http://0.0.0.0:12345"
include_tx_body = false
