private_key = "1212121212121212121212121212121212121212121212121212121212121212"
min_soft_confirmations_per_commitment = 10
test_mode = false
deposit_mempool_fetch_limit = 10
block_production_interval_ms = 1000
da_update_interval_ms = 2000

# pruning_config.distance = 10

[mempool_conf] # Mempool Configuration - https://github.com/ledgerwatch/erigon/wiki/Transaction-Pool-Design
pending_tx_limit = 100000
pending_tx_size = 200
queue_tx_limit = 100000
queue_tx_size = 200
base_fee_tx_limit = 100000
base_fee_tx_size = 200
max_account_slots = 16
