[public_keys]
sequencer_public_key = "204040e364c10f2bec9c1fe500a1cd4c247c89d650a01ed7e82caba867877c21"
sequencer_da_pub_key = "0000000000000000000000000000000000000000000000000000000000000000"
prover_da_pub_key = ""

[da]
sender_address = "0000000000000000000000000000000000000000000000000000000000000000"
db_path = "resources/dbs/da-db"

[storage]
# The path to the rollup's data directory. Paths that do not begin with `/` are interpreted as relative paths.
path = "resources/dbs/sequencer-db"
db_max_open_files = 5000

[rpc]
# the host and port to bind the rpc server for
bind_host = "127.0.0.1"
bind_port = 12345
max_connections = 10000
enable_subscriptions = true
max_subscriptions_per_connection = 100
