[package]
name = "risc0"
version = "0.4.0-rc.3"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
resolver = "2"

[build-dependencies]
risc0-build = { workspace = true }

[package.metadata.risc0]
methods = ["guest-mock", "guest-bitcoin"]

[features]
bench = []
